version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      asellion:
        ipv4_address: 172.20.1.2
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: asellion
    ports:
      - 3306:3306
  adminer:
    image: adminer
    restart: always
    ports:
      - 8989:8080
  asellion-service:
    image: asellion/app
    depends_on:
      - db
    ports:
      - 8080:8080
networks:
  asellion:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.1.0/24