version: '3.1'

services:

  mysqldb:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      asellion:
        ipv4_address: 172.20.1.2
    healthcheck:
      test: mysql -e "SHOW VARIABLES" -u root >/dev/null 2>&1;
      timeout: 20s
      retries: 10
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: asellion
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - 3306:3306
  adminer:
    image: adminer
    restart: always
    ports:
      - 8989:8080
  asellion-service:
    image: asellion/app
    restart: always
    depends_on:
      - flyway
    ports:
      - 8080:8080
    networks:
      asellion:
  flyway:
    image: flyway/flyway
    command: -url=jdbc:mysql://mysqldb/asellion?useSSL=false -schemas=asellion -user=root -password=password -connectRetries=60 migrate
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    depends_on:
      - mysqldb
    networks:
      asellion:
networks:
  asellion:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.1.0/24